'''
    to clean the images generated by the mdcam2
'''
pattern = r".png"

import os
import re

files = os.listdir(".")

for file in files:
    found = re.search(pattern, file)
    if found:
        os.remove(file)